package com.dr10.common.utilities

object Constants {
    const val DEFAULT_PROJECTS_DIRECTORY_NAME = "DeepCodeProjects"
    const val DEFAULT_DATABASE_DIRECTORY_NAME = ".data"
    const val DEFAULT_LOCAL_DIRECTORY_NAME = ".local/share/DeepCodeStudio"
    const val JAVA_DIRECTORY_NAME = "java"
    const val CLASSES_DIRECTORY_NAME = "classes"
    const val DATABASE_NAME = "AppDatabase.db"

    const val JFLEX_EXTENSION = ".flex"
    const val JAVA_EXTENSION = ".java"
    const val JAVA_CLASS_EXTENSION = ".class"

    const val DEFAULT_JFLEX_CLASS_NAME = "TokenMarkerTemplate"
    const val CLASS_EXTENSION = "TokenMarker"
    const val INSTRUCTIONS_IDENTIFIER = "{{INSTRUCTIONS}}"
    const val VARIABLES_IDENTIFIER = "{{VARIABLES}}"
    const val CONSTANTS_IDENTIFIER = "{{CONSTANTS}}"
    const val SEGMENTS_IDENTIFIER = "{{SEGMENTS}}"
    const val SYSTEM_CALLS_IDENTIFIER = "{{SYSTEM_CALLS}}"
    const val REGISTERS_IDENTIFIER = "{{REGISTERS}}"
    const val ARITH_INSTRUCTIONS_IDENTIFIER = "{{ARITH_INSTRUCTIONS}}"
    const val LOGICAL_INSTRUCTIONS_IDENTIFIER = "{{LOGICAL_INSTRUCTIONS}}"
    const val CONDITIONS_IDENTIFIER = "{{CONDITIONS}}"
    const val MEMORY_MANAGEMENTS_IDENTIFIER = "{{MEMORY_MANAGEMENTS}}"

    const val DEFAULT_SIMPLE_COLOR = "#ABB2BF"
    const val DEFAULT_INSTRUCTION_COLOR = "#C678DD"
    const val DEFAULT_CONSTANT_COLOR = "#61AFEF"
    const val DEFAULT_STRING_COLOR = "#98C379"
    const val DEFAULT_VARIABLE_COLOR = "#61AFEF"
    const val DEFAULT_LABEL_COLOR = "#56B6C2"
    const val DEFAULT_NUMBER_COLOR = "#D19A66"
    const val DEFAULT_SEGMENT_COLOR = "#56B6C2"
    const val DEFAULT_SYSTEM_CALL_COLOR = "#ABB2BF"
    const val DEFAULT_REGISTER_COLOR = "#C678DD"
    const val DEFAULT_ARITHMETIC_INSTRUCTION_COLOR = "#C678DD"
    const val DEFAULT_LOGICAL_INSTRUCTION_COLOR = "#C678DD"
    const val DEFAULT_CONDITION_COLOR = "#C678DD"
    const val DEFAULT_LOOP_COLOR = "#C678DD"
    const val DEFAULT_MEMORY_MANAGEMENT = "#C678DD"
    const val DEFAULT_COMMENT_COLOR = "#5C6370"
}