package com.dr10.common.utilities

object Constants {
    const val DEFAULT_PROJECTS_DIRECTORY_NAME = "DeepCodeProjects"
    const val DEFAULT_LINUX_LOCAL_DIRECTORY_NAME = ".local/share/DeepCodeStudio"
    const val DEFAULT_WINDOWS_LOCAL_DIRECTORY_NAME = "AppData/Local/DeepCodeStudio"
    const val DEFAULT_ASM_SYNTAX_NAME = "defaultAssemblerSyntax"
    const val JAVA_DIRECTORY_NAME = "java"
    const val CLASSES_DIRECTORY_NAME = "classes"
    const val DATABASE_NAME = "AppDatabase.db"

    const val JFLEX_EXTENSION = ".flex"
    const val JAVA_EXTENSION = ".java"
    const val JAVA_CLASS_EXTENSION = ".class"

    const val DEFAULT_JFLEX_CLASS_NAME = "TokenMarkerTemplate"
    const val CLASS_EXTENSION = "TokenMarker"
    const val INSTRUCTIONS_IDENTIFIER = "{{INSTRUCTIONS}}"
    const val VARIABLES_IDENTIFIER = "{{VARIABLES}}"
    const val CONSTANTS_IDENTIFIER = "{{CONSTANTS}}"
    const val SEGMENTS_IDENTIFIER = "{{SEGMENTS}}"
    const val SYSTEM_CALLS_IDENTIFIER = "{{SYSTEM_CALLS}}"
    const val REGISTERS_IDENTIFIER = "{{REGISTERS}}"
    const val ARITH_INSTRUCTIONS_IDENTIFIER = "{{ARITH_INSTRUCTIONS}}"
    const val LOGICAL_INSTRUCTIONS_IDENTIFIER = "{{LOGICAL_INSTRUCTIONS}}"
    const val CONDITIONS_IDENTIFIER = "{{CONDITIONS}}"
    const val MEMORY_MANAGEMENTS_IDENTIFIER = "{{MEMORY_MANAGEMENTS}}"

    const val DEFAULT_SIMPLE_COLOR = "171,178,191"
    const val DEFAULT_COMMENT_COLOR = "92,99,112"
    const val DEFAULT_RESERVED_WORD_COLOR = "181,126,220"
    const val DEFAULT_RESERVED_WORD_2_COLOR = "86,182,194"
    const val DEFAULT_NUMBER_COLOR = "209,154,102"
    const val DEFAULT_HEX_COLOR = "229,192,123"
    const val DEFAULT_FUNCTION_COLOR = "97,175,239"
    const val DEFAULT_STRING_COLOR = "152,195,121"
    const val DEFAULT_DATA_TYPE_COLOR = "93,173,226"
    const val DEFAULT_VARIABLE_COLOR = "224,108,117"
    const val DEFAULT_OPERATOR_COLOR = "116,138,166"
    const val DEFAULT_PROCESSOR_COLOR = "179,157,219"

    const val SIMPLE = "Simple"
    const val COMMENT = "Comment"
    const val RESERVED_WORD = "Reserved Word"
    const val RESERVED_WORD_2 = "Reserved Word 2"
    const val HEXADECIMAL = "Hexadecimal"
    const val NUMBER = "Number"
    const val FUNCTION = "Function"
    const val STRING = "String"
    const val DATA_TYPE = "Data Type"
    const val VARIABLE = "Variable"
    const val OPERATOR = "Operator"
    const val PROCESSOR = "Processor"
}