package domain.util

object Constants {
    const val DEFAULT_PROJECTS_DIRECTORY_NAME = "DeepCodeProjects"

    const val DEFAULT_SIMPLE_COLOR = "#ABB2BF"
    const val DEFAULT_INSTRUCTION_COLOR = "#C678DD"
    const val DEFAULT_CONSTANT_COLOR = "#61AFEF"
    const val DEFAULT_STRING_COLOR = "#98C379"
    const val DEFAULT_VARIABLE_COLOR = "#61AFEF"
    const val DEFAULT_LABEL_COLOR = "#56B6C2"
    const val DEFAULT_NUMBER_COLOR = "#D19A66"
    const val DEFAULT_SEGMENT_COLOR = "#56B6C2"
    const val DEFAULT_SYSTEM_CALL_COLOR = "#ABB2BF"
    const val DEFAULT_REGISTER_COLOR = "#C678DD"
    const val DEFAULT_ARITHMETIC_INSTRUCTION_COLOR = "#C678DD"
    const val DEFAULT_LOGICAl_INSTRUCTION_COLOR = "#C678DD"
    const val DEFAULT_CONDITION_COLOR = "#C678DD"
    const val DEFAULT_LOOP_COLOR = "#C678DD"
    const val DEFAULT_MEMORY_MANAGEMENT = "#C678DD"
    const val DEFAULT_COMMENT_COLOR = "#5C6370"
}